import {
  beneficiaries,
  reportHistory as seedReportHistory,
  reportTemplates,
  type ReportFormat,
  type ReportHistoryEntry,
  type ReportHistoryType,
  type ReportTemplate,
} from '../data/mockData'
import { formatAuditDate } from './auditStorage'
import { getAssistanceItems } from './decisionStorage'
import { getAuditLogs } from './auditStorage'
import { downloadCsv, formatExportDateStamp } from '../utils/csvExport'

const REPORT_HISTORY_KEY = 'barangay_report_history'
const UPDATED_EVENT = 'report-history-updated'

export type ReportPreviewSection = {
  heading: string
  lines: string[]
}

export type ReportPreview = {
  entry: ReportHistoryEntry
  sections: ReportPreviewSection[]
}

function readHistory(): ReportHistoryEntry[] {
  const raw = localStorage.getItem(REPORT_HISTORY_KEY)
  if (!raw) return []
  try {
    return JSON.parse(raw) as ReportHistoryEntry[]
  } catch {
    return []
  }
}

function writeHistory(entries: ReportHistoryEntry[]) {
  localStorage.setItem(REPORT_HISTORY_KEY, JSON.stringify(entries))
  window.dispatchEvent(new CustomEvent(UPDATED_EVENT))
}

export function initializeReportHistoryStorage() {
  if (!localStorage.getItem(REPORT_HISTORY_KEY)) {
    writeHistory(seedReportHistory)
  }
}

export function getReportHistory(): ReportHistoryEntry[] {
  initializeReportHistoryStorage()
  return readHistory()
}

export function subscribeReportHistory(callback: () => void) {
  const handler = () => callback()
  window.addEventListener(UPDATED_EVENT, handler)
  return () => window.removeEventListener(UPDATED_EVENT, handler)
}

export function getReportTemplateByTitle(title: string): ReportTemplate | null {
  return reportTemplates.find((template) => template.title === title) ?? null
}

function extensionForFormat(format: ReportFormat): string {
  if (format === 'PDF') return 'pdf'
  if (format === 'EXCEL') return 'xlsx'
  return 'csv'
}

function buildFileName(template: ReportTemplate, format: ReportFormat): string {
  const stamp = formatExportDateStamp()
  return `${template.slug}_${stamp}.${extensionForFormat(format)}`
}

function createHistoryEntry(
  template: ReportTemplate,
  generatedBy: string,
  format: ReportFormat,
): ReportHistoryEntry {
  const timestamp = new Date().toISOString()
  return {
    id: crypto.randomUUID(),
    name: buildFileName(template, format),
    generatedBy,
    date: formatAuditDate(timestamp),
    format,
    reportType: template.reportType,
  }
}

function prependHistory(entry: ReportHistoryEntry): ReportHistoryEntry {
  writeHistory([entry, ...readHistory()])
  return entry
}

export function generateReportFromTemplate(
  template: ReportTemplate,
  generatedBy: string,
): ReportHistoryEntry {
  return prependHistory(createHistoryEntry(template, generatedBy, 'PDF'))
}

export function exportReportFromTemplate(
  template: ReportTemplate,
  generatedBy: string,
  format: ReportFormat,
): ReportHistoryEntry {
  const entry = prependHistory(createHistoryEntry(template, generatedBy, format))
  downloadHistoryReport(entry)
  return entry
}

function entryById(id: string): ReportHistoryEntry | null {
  return getReportHistory().find((row) => row.id === id) ?? null
}

export function buildReportPreview(entry: ReportHistoryEntry): ReportPreview {
  const sections: ReportPreviewSection[] = [
    {
      heading: 'Report Information',
      lines: [
        `File: ${entry.name}`,
        `Generated by: ${entry.generatedBy}`,
        `Date: ${entry.date}`,
        `Format: ${entry.format}`,
      ],
    },
  ]

  switch (entry.reportType) {
    case 'beneficiary':
      sections.push({
        heading: 'Beneficiary Summary',
        lines: beneficiaries.map(
          (b) =>
            `${b.name} | ${b.association} | Family ${b.familySize} | ${b.vulnerability} vulnerability`,
        ),
      })
      break
    case 'vulnerability':
      sections.push({
        heading: 'Vulnerability Highlights',
        lines: beneficiaries.map(
          (b) => `${b.association} — ${b.name}: ${b.vulnerability} (${b.housing}, income indexed)`,
        ),
      })
      break
    case 'assistance':
      sections.push({
        heading: 'Assistance Requests',
        lines: getAssistanceItems().map(
          (item) => `${item.association} | ${item.requestType} | ${item.status} | ${item.date}`,
        ),
      })
      break
    case 'approved':
      sections.push({
        heading: 'Approved Assistance',
        lines: getAssistanceItems()
          .filter((item) => item.status === 'APPROVED')
          .map(
            (item) => `${item.association} | ${item.requestType} | Approved | ${item.date}`,
          ),
      })
      break
    case 'ai_scoring':
      sections.push({
        heading: 'AI Assessment Events',
        lines: getAuditLogs()
          .filter((log) => log.action.includes('Assessment') || log.action.includes('Approval'))
          .slice(0, 12)
          .map((log) => `${log.date} — ${log.action}: ${log.description}`),
      })
      break
    case 'audit':
      sections.push({
        heading: 'Audit Log Entries',
        lines: getAuditLogs()
          .slice(0, 15)
          .map((log) => `${log.date} — ${log.user}: ${log.action}`),
      })
      break
    default:
      break
  }

  return { entry, sections }
}

export function getReportPreviewById(id: string): ReportPreview | null {
  const entry = entryById(id)
  if (!entry) return null
  return buildReportPreview(entry)
}

function csvRowsForEntry(entry: ReportHistoryEntry): { headers: string[]; rows: (string | number)[][] } {
  switch (entry.reportType) {
    case 'beneficiary':
      return {
        headers: ['Name', 'Association', 'Family Size', 'Monthly Income', 'Vulnerability', 'Status'],
        rows: beneficiaries.map((b) => [
          b.name,
          b.association,
          b.familySize,
          b.monthlyIncome,
          b.vulnerability,
          b.status,
        ]),
      }
    case 'vulnerability':
      return {
        headers: ['Name', 'Association', 'Vulnerability', 'Housing', 'Elderly', 'PWD'],
        rows: beneficiaries.map((b) => [
          b.name,
          b.association,
          b.vulnerability,
          b.housing,
          b.elderly,
          b.pwd,
        ]),
      }
    case 'assistance':
      return {
        headers: ['Association', 'Request Type', 'Status', 'Date', 'Vulnerability'],
        rows: getAssistanceItems().map((item) => [
          item.association,
          item.requestType,
          item.status,
          item.date,
          item.vulnerability,
        ]),
      }
    case 'approved':
      return {
        headers: ['Association', 'Request Type', 'Status', 'Date', 'Vulnerability'],
        rows: getAssistanceItems()
          .filter((item) => item.status === 'APPROVED')
          .map((item) => [
            item.association,
            item.requestType,
            item.status,
            item.date,
            item.vulnerability,
          ]),
      }
    case 'ai_scoring':
      return {
        headers: ['Date', 'User', 'Action', 'Description'],
        rows: getAuditLogs()
          .filter((log) => log.action.includes('Assessment') || log.action.includes('Approval'))
          .slice(0, 25)
          .map((log) => [log.date, log.user, log.action, log.description]),
      }
    case 'audit':
      return {
        headers: ['Date', 'User', 'Action', 'Description', 'IP Address'],
        rows: getAuditLogs().slice(0, 50).map((log) => [
          log.date,
          log.user,
          log.action,
          log.description,
          log.ipAddress,
        ]),
      }
    default:
      return { headers: ['Note'], rows: [['No export data available.']] }
  }
}

export function downloadHistoryReport(entry: ReportHistoryEntry): void {
  const { headers, rows } = csvRowsForEntry(entry)
  const fileName = entry.name.replace(/\.(pdf|xlsx)$/i, '.csv')
  downloadCsv(fileName, headers, rows)
}

export function reportTypeLabel(type: ReportHistoryType): string {
  switch (type) {
    case 'beneficiary':
      return 'Beneficiary'
    case 'vulnerability':
      return 'Vulnerability'
    case 'assistance':
      return 'Assistance'
    case 'approved':
      return 'Approved Assistance'
    case 'ai_scoring':
      return 'AI Assessment'
    case 'audit':
      return 'Audit Log'
    default:
      return 'Report'
  }
}
