import {
  Users,
  Shield,
  HandHeart,
  Cpu,
  CheckCircle,
  FileText,
  ChevronDown,
} from 'lucide-react'
import { AdminHeader } from '../../components/admin/AdminHeader'
import { AnalyticsCharts } from '../../components/admin/AnalyticsCharts'
import { reportTemplates, reportHistory } from '../../data/mockData'

const iconMap = {
  users: Users,
  shield: Shield,
  hand: HandHeart,
  cpu: Cpu,
  check: CheckCircle,
  file: FileText,
}

export default function ReportsPage() {
  return (
    <>
      <AdminHeader title="System Reports Panel" />
      <main className="flex-1 overflow-y-auto p-4 sm:p-5 md:p-6">
        <div className="mb-8">
          <h2 className="text-base font-bold text-gray-900">Assistance Analytics</h2>
          <p className="mt-1 text-sm text-gray-500">
            Program matching, request status, and distribution performance at a glance.
          </p>
          <div className="mt-5">
            <AnalyticsCharts />
          </div>
        </div>

        <div className="mb-8">
          <h2 className="text-base font-bold text-gray-900">Available Assistance Reports</h2>
          <p className="mt-1 text-sm text-gray-500">
            Select and configure templates to generate localized reports.
          </p>

          <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {reportTemplates.map((report) => {
              const Icon = iconMap[report.icon as keyof typeof iconMap]
              return (
                <div
                  key={report.title}
                  className="rounded-lg border border-gray-200 bg-white p-5 shadow-sm"
                >
                  <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg bg-green-50">
                    <Icon className="h-5 w-5 text-primary" />
                  </div>
                  <h3 className="font-bold text-gray-900">{report.title}</h3>
                  <p className="mt-1 text-sm text-gray-500">{report.description}</p>
                  <div className="mt-4 flex gap-2">
                    <button
                      type="button"
                      className="rounded-lg border border-gray-200 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
                    >
                      Generate Report
                    </button>
                    <button
                      type="button"
                      className="flex items-center gap-1 rounded-lg border border-gray-200 px-3 py-1.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
                    >
                      Export As
                      <ChevronDown className="h-3 w-3" />
                    </button>
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        <div className="rounded-lg border border-gray-200 bg-white shadow-sm">
          <div className="border-b border-gray-200 px-5 py-4">
            <h2 className="text-base font-bold text-gray-900">Report History</h2>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100 bg-gray-50 text-left text-xs font-semibold uppercase text-gray-500">
                  <th className="px-4 py-3">Report Name</th>
                  <th className="px-4 py-3">Generated By</th>
                  <th className="px-4 py-3">Date</th>
                  <th className="px-4 py-3">Format</th>
                  <th className="px-4 py-3">Actions</th>
                </tr>
              </thead>
              <tbody>
                {reportHistory.map((row) => (
                  <tr key={row.name} className="border-b border-gray-50 hover:bg-gray-50">
                    <td className="px-4 py-3 font-medium text-gray-900">{row.name}</td>
                    <td className="px-4 py-3 text-gray-600">{row.generatedBy}</td>
                    <td className="px-4 py-3 text-gray-500">{row.date}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`font-semibold ${
                          row.format === 'PDF' ? 'text-red-600' : 'text-green-600'
                        }`}
                      >
                        {row.format}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex gap-3">
                        <button type="button" className="text-sm font-semibold text-primary hover:underline">
                          View
                        </button>
                        <button type="button" className="text-sm font-semibold text-primary hover:underline">
                          Download
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </>
  )
}
